### PR TITLE
Make System Parachains trusted Teleporters

### PR DESCRIPTION
**Pull request by NachoPal**
Make System Parachain trusted Teleporters of each other. System Parachains should be able to teleport their native asset between them.

Depends on: https://github.com/paritytech/polkadot-sdk/pull/1368

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Review by bkontur — APPROVED** [review]

**Review by xlc — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Comment by bkchr** [comment]
@NachoPal please fix compilation. The type is probably not yet available, so best to copy it.

**Comment by bkontur** [comment]
> @NachoPal please fix compilation. The type is probably not yet available, so best to copy it.

@NachoPal in case of copy, `ConcreteAssetFromSystem` depends on `ParaId::from(*id).is_system()` which has been changed [here](https://github.com/paritytech/polkadot-sdk/pull/1406/files#diff-0b7b4f5b962a18ce980354592b55ab2a27b5a2e9f6f8089ec803ca73853e8583L202-R203). If this constant change is not part of actual  [`polkadot-parachain-primitives` dependency](https://github.com/polkadot-fellows/runtimes/blob/main/Cargo.lock#L7773C1-L7777) (looks like [v1.0.0](https://docs.rs/polkadot-parachain-primitives/1.0.0/src/polkadot_parachain_primitives/primitives.rs.html#226) it is not, only [v2.0.0](https://docs.rs/polkadot-parachain-primitives/2.0.0/src/polkadot_parachain_primitives/primitives.rs.html#224) has it), so you should better go with `< 2000`,

**Comment by NachoPal** [comment]
@bkontur Yeah, I talked to @bkchr, and IMHO unless it is a bug fix that needs to be asap in the next release, better to avoid this kind of patching that can potentially lead to errors in the future.

This PR will wait to be merged until the missing type is available.

**Comment by bkchr** [comment]
Was already done in: https://github.com/polkadot-fellows/runtimes/pull/87

**Pull request closed without merging**
