### PR TITLE
CI: use GitHub native concurrency to cancel workflows

### PR DESCRIPTION
**Pull request by acatangiu**
Don't install/use custom [styfle/cancel-workflow-action](https://github.com/styfle/cancel-workflow-action) actions.

Instead, use the GitHub native [concurrency](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/) property to cancel workflows.

- [x] Does not require a CHANGELOG entry

### CODE REVIEW

**Comment by acatangiu** [comment]
@alvicsam looks like merged https://github.com/polkadot-fellows/runtimes/pull/142 had overlap with this PR - please take a look here and see if the remaining "diff" is worth merging. I will close it otherwise.

**Comment by bkchr** [comment]
@alvicsam @acatangiu do we still need this?

**Review by bkchr — APPROVED** [review]

**Review by xlc — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by acatangiu** [comment]
This doesn't need a changelog, but how do we bypass the CI check for it?

**Pull request merged**
