### PR TITLE
Bump ParachainHost to api version 10 on kusama

### PR DESCRIPTION
**Pull request by alexggh**
... to add approval_voting_params API which will allow us to enable approvals coalescing implementation from:
 - https://github.com/paritytech/polkadot-sdk/pull/1191

Note! Bumping the version will not enable the new logic, that will be enable at a later date we we decide to call set_approval_voting_params with max_approval_coalesce_count greater than 1.

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Review by AndreiEres — APPROVED** [review]

**Review by bkontur — APPROVED** [review]

**Comment by alexggh** [comment]
@bkontur any idea if the following failed check, is something to worry about ? It did not start with this PR, but better ask than being sorry :D
>Check Migrations / check-migrations (encointer-kusama, encointer-kusama-runtime, system

**Comment by bkontur** [comment]
> @bkontur any idea if the following failed check, is something to worry about ? It did not start with this PR, but better ask than being sorry :D
> 
> > Check Migrations / check-migrations (encointer-kusama, encointer-kusama-runtime, system

@alexggh no worries, it is a known issue: https://github.com/polkadot-fellows/runtimes/pull/159#issuecomment-1966836443

**Comment by alexggh** [comment]
> @alexggh no worries, it is a known issue: [#159 (comment)](https://github.com/polkadot-fellows/runtimes/pull/159#issuecomment-1966836443)

Yeah, but it seems I can't merge the stuff without it passing because it is required, @bkchr any chance you can use your super powers to merge this. Thank you!

**Pull request merged**
