### PR TITLE
`im-online` cleanup: phase 1

### PR DESCRIPTION
**Pull request by s0me0ne-unkn0wn**
This PR removes migrations and transient code connected with `im-online` removal. It introduces an offchain db cleanup migration that must be removed later.

- [x] Does not require a CHANGELOG entry

### CODE REVIEW

**Comment by s0me0ne-unkn0wn** [comment]
Currently, this PR suffers from a versioning problem (it requires `pallet-im-online` version 30.0.0, which brings in diverged dependencies). I'll wait until the 1.3.0 version bumps are complete before proceeding with this one.

**Comment by s0me0ne-unkn0wn** [comment]
It was finally unblocked by bumping SDK to 1.13
CC @ordian

**Review by ordian — APPROVED** [review]
The last phase would be removing this code?

**Comment by s0me0ne-unkn0wn** [comment]
> The last phase would be removing this code?

Exactly, and after that we're done (I'm expecting some big celebration in connection with that event)

**Comment by ordian** [comment]
cc @eskimor @sandreim

**Review by acatangiu — APPROVED** [review]
Nice!

**Review by bkchr — APPROVED** [review]

**Pull request merged**
