### PR TITLE
Fixup some release issues edition 2

### PR DESCRIPTION
**Pull request by bkchr**
- Rename the release workflow
- Fixup the upload path in the release upload job
- Adds one missing CHANGELOG entry
- Drop tx version in the file names

### CODE REVIEW

**Review by bkontur — APPROVED** [review]

**Review by joepetrowski — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
The release notes still mention `Statemint` and `Statemine`.

**Comment by bkchr** [comment]
> The release notes still mention `Statemint` and `Statemine`.

Should be done here: https://github.com/polkadot-fellows/runtimes/pull/71

**Review by andresilva — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by liamaharon** [comment]
> > The release notes still mention `Statemint` and `Statemine`.
> 
> Should be done here: #71

Are you thinking I should just fix the specnames in my PR (breaking change) or add special handing in the release script for `statemint` and `statemine`?

**Review by shawntabrizi — APPROVED** [review]

**Pull request merged**
