### PR TITLE
Keep `im-online` events decodable after pallet removal

### PR DESCRIPTION
**Pull request by s0me0ne-unkn0wn**
This is a follow-up to #178, which aims to keep the `im-online` pallet events decodable after the pallet itself is removed.

As [discussed](https://github.com/polkadot-fellows/runtimes/pull/178#issuecomment-1977608363), the inability to decode events may result in missing a candidate in approval voting and a parachain finality stall. Although the circumstances of such an event are unlikely, it's better to safeguard them.

The transient code introduced in this PR should be removed after the upgrade is enacted.

- [x] Does not require a CHANGELOG entry

### CODE REVIEW

**Review by eskimor — APPROVED** [review]
Looks sensible to me, assuming it was tested to actually work. (E.g. does the pallet path matter?)

**Comment by s0me0ne-unkn0wn** [comment]
> assuming it was tested to actually work

Yes, I reproduced the problem in a local synthetic test and made sure it was resolved with this patch. Paths do not matter, TypeInfo only includes names, I'm not sure it's even critical in this case, but I still named the thing `pallet_im_online` to be on the safe side.

**Review by ordian — APPROVED** [review]
This is a reasonable workaround. I assume we can safely remove this mock pallet after the runtime upgrade is applied (let's create an issue to not forget)?

**Comment by s0me0ne-unkn0wn** [comment]
> I assume we can safely remove this mock pallet after the runtime upgrade is applied (let's create an issue to not forget)?

Fair enough, raised #242

**Comment by bkchr** [comment]
Thank you! Good approach!

**Pull request merged**
