### PR TITLE
🚨 [Collectives] Add TX payment extension

### PR DESCRIPTION
**Pull request by ggwpez**
🚨 Breaking Change 🚨
- This adds a signed extension for the polkadot-collectives runtime which will break transaction encoding.

Status: waiting for https://github.com/polkadot-fellows/runtimes/pull/445

### CODE REVIEW

**Review by skunert — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by joepetrowski** [comment]
@Imod7 @SBalaguer @anaelleltd please notify wallets, this will be a breaking change for transaction encoding.

**Comment by anaelleltd** [comment]
The author of a PR that introduces a breaking change should:
- recommend a course of action for builders/teams to follow up
- highlight the nature of this breaking change more prominently in the CHANGELOG

The rationale for these additional steps is available [here](https://github.com/polkadot-fellows/runtimes/issues/441).

**Pull request merged**
