### PR TITLE
Clean up genesis config presets for all runtimes

### PR DESCRIPTION
**Pull request by seadanda**
This PR does three things related to chain-specs and genesis config presets:
- Refactor `preset_names` to `genesis_config_presets` in all runtimes as suggested for the Polkadot Coretime runtime in #410.
- Make the chain-spec generator use the preset from the WASM directly for each runtime.
- Propagate the `on_chain_release_build` feature to the chain-spec generator. Without this we cannot generate live/genesis chain-specs with the chain-spec generator without having to post-process it to replace the WASM compiled with this flag.

### CODE REVIEW

**Review by muharem — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by kianenigma** [comment]
Why does the fellowship repo have this `chain-spec generator` and not use OG chain-spec-builder? 

Sorry of this is duplicate, I think I have heard an explanation of this recently, but I can't recall it.

**Comment by bkchr** [comment]
> Why does the fellowship repo have this `chain-spec generator` and not use OG chain-spec-builder?

Historical reasons. We don't really need it anymore. Someone just needs to remove it.

**Comment by bkontur** [comment]
> Why does the fellowship repo have this `chain-spec generator` and not use OG chain-spec-builder?
> 
> Sorry of this is duplicate, I think I have heard an explanation of this recently, but I can't recall it.

> Historical reasons. We don't really need it anymore. Someone just needs to remove it.


@bkchr @kianenigma https://github.com/polkadot-fellows/runtimes/issues/395

**Pull request merged**
